language: go
go:
  - "1.13.4"
env:
  - GO111MODULE=on
before_script:
  - go mod vendor
script:
  - make publish
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: "MV9AQhH4+r8KKmpH9qYTVnYXwFmPmIm4xcZk+zmvc5N6pmQL/l5WM14hKzSusTAnNhHpPKOcwUtCSjadxBo4g1QdCGC0M0GLq6z41KUeoVK5CUr/XLKQiQBnZGkb/2DVJ/7Af80uu+F34Ho3VXtZ0CPpQiyrp0nw4Ib2ZB4Wke1NpgeIX8DPgGCasrqObKp8q6bgw0bEFxmqe2yaKdj4eQ44/XS1JyrZVMRW433WKFvn8G0Y1ILH7VzgYRbdyyHXLgUirRAPI/3RQiEUSDdPjjPefQis+YVk/qmCKIQkEcBa61KI1MS1ltW6eVBt74gHJFZKb2KLoK5DLfiF0UrP19v0N7F2PnKXua3sZLLsg+ba3yurrXCKkqOmNdr6r+7KYxON33v6RwPc5Qfa6uoONT188ST5e1LaU6JZ5pX1MMMSIO5zm5xeQapztTJHAK6YkQmm5F1ixfphyBpLHVfa86mTGEVxtCBQ90HI6keSkOZ/7Va1HCOKBlS0zQAldB5F9nfc/cdEOSDUnrFWYc7FCkEXN4gpqhyH3U8cQ2kEvJao3ACDxQUyzzMHooEmu/2g5mOfp4m1NN0YZiHNjQ+OyRwNpapueSf39rCOTbLO2FPCcmJeqNFMgSiT+unj4fIFdfpqCwJJEQS/15j8K9eau3+Lawvq07OGH+tCuiyWQas="
  file:
    - bin/biter-mac
    - bin/biter
    - bin/biter.exe
  skip_cleanup: true
  on:
    tags: true