language: go
go:
  - "1.13.4"
cache:
  - vendor/
env:
  - GO111MODULE=on
before_script:
  - go mod vendor
script:
  - make publish
deploy:
  provider: releases
  overwrite: true
  api_key:
    secure: $GITHUB_TOKEN
  file:
    - bin/poker-mac
    - bin/poker
    - bin/poker.exe
  skip_cleanup: true
  on:
    tags: true